version: '3.0'

services:
  alumni:
    build: .
    ports:
      - "8080:8080"
    volumes:
      - .:/var/www/app
      - ./data:/var/www/app/data #following the host:VM machine pattern this allows us to decouple the data directory from the app dir itself. Following proper microservice architecture
    environment:
      TZ: "America/New York"
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:5 #build changed to 5 for release stability managment 
    ports:
      - "8081:80"
    depends_on:
      - db

  db:
    image: mariadb:10.1
    volumes:
        - ./alumni.sql:/docker-entrypoint-initdb.d/init.sql:ro
        - ./database/:/var/lib/mysql
    ports:
      - "3307:3306"
    environment:
        TZ: "America/New York"
        MYSQL_USER: ${USERNAME?USERNAME variable not set}
        MYSQL_PASSWORD: ${PASSWORD?PASSWORD variable not set}
        MYSQL_ROOT_PASSWORD: ${ROOTPASSWORD?ROOTPASSWORD variable not set}
